### ISSUE TITLE
Does this support git packages that depend on other git packages?

### ISSUE THREAD

**Issue by Esildor** [mob-sakai/GitDependencyResolverForUnity#14]
For example:
{
    "name": "https://github.com/me/Foo.git#1.0.0",
    "dependencies": {
        "https://github.com/me/Bar.git": "2.0.0"
}
}

**Comment by mob-sakai** [comment]
Hi @Esildor 
No, this plugin does not support that format.
(That format is not supported by Unity Package Manager.)

This plugin supports the following formats:
```js
{
  "name": "me.foo",
  "dependencies": {
    "me.bar": "https://github.com/me/Bar.git#2.0.0"
  }
}
```
`Bar.git` has branch or tag named `2.0.0` and contains `package.json` in root.

**Comment by Esildor** [comment]
So its not possible have a git package depend on (and automatically import) another git package. Got it, thanks! 👍
