### ISSUE TITLE
guids for git-dependency-resolver conflict with upm-git-extension

### ISSUE THREAD

**Issue by Fuzzy-Logik** [mob-sakai/GitDependencyResolverForUnity#15]
Unity 2018.3.02f
upm-git-extension 0.9.1
git-dependency-resolver 1.1.0

> GUID [06608ad179f2043e5a26ec668de262d6] for asset 'Packages/com.coffee.git-dependency-resolver/CHANGELOG.md' conflicts with:
>   'Packages/com.coffee.upm-git-extension/CHANGELOG.md'
> We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.
>

Examining CHANGELOG.md.meta (using the github interface) on both the git-depency-resolver and the upm-git-extension repositories shows that they have the same GUID:
```
guid: 06608ad179f2043e5a26ec668de262d6
```

Normally Unity would generate a new meta file but because the packages are in the PackageCache, they are immutable.

This error occurs for many files.

**Comment by mob-sakai** [comment]
Hi @Fuzzy-Logik 
Thank you for your reporting.

I will fix them ASAP. :)

**Comment by Fuzzy-Logik** [comment]
Hey, I didn't want to open a new issue but release 1.1.1 is broken. Many files are missing, such as the asmdef and the entire Editor folder.
Also thanks for the tools! They are useful.

**Comment by mob-sakai** [comment]
Oh, sorry...

**Comment by mob-sakai** [comment]
I released 1.1.2.
Please try it!

**Comment by Fuzzy-Logik** [comment]
I installed 1.1.2 and everything appears to be OK now. Thanks
It installs without any warnings or errors.

**Comment by mob-sakai** [comment]
:+1:
