### ISSUE TITLE
Some files in GitDependencyResolverForUnity conflicts with UpmGitExtension

### ISSUE THREAD

**Issue by dimmduh** [mob-sakai/GitDependencyResolverForUnity#16]
Version 'https://my.gitlab.com/npm/test.git#1.1.1' is invalid. Expected a 'SemVer' compatible value. (NotFound)

{
	"name": "com.test",
	"displayName": "My test",
	"version": "2.1.4",
	"unity": "2019.1",
	"description": "above. ",
	"dependencies": {
	    "com.test22": "https://gitlab.io-games.com/npm/test.git#1.1.1"
	}
}

**Comment by dimmduh** [comment]
Removing library folder does not help.

**Comment by mob-sakai** [comment]
Hi @dimmduh 
I would like to know more information on this issue.

**Environment (please complete the following information):**
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac)]
 - Unity: [e.g. 2018.3.0f1]
 - GitDependencyResolverForUnity: [e.g. v1.1.2]

**Comment by dimmduh** [comment]
Windows 7 SP1
Unity 20191.10f1
v1.1.2

**Comment by starikcetin** [comment]
I am also experiencing this:

```
Error: Unable to add package [com.starikcetin.eflatun.unitycommon@https://github.com/starikcetin/Eflatun.UnityCommon.git#0.0.1-upm]:
  Package com.starikcetin.eflatun.unitycommon@https://github.com/starikcetin/Eflatun.UnityCommon.git#0.0.1-upm has invalid dependencies:
    com.starikcetin.eflatun.expansions: Version 'https://github.com/starikcetin/Eflatun.Expansions.git#0.1.0-upm' is invalid. Expected a 'SemVer' compatible value. (NotFound)
UnityEngine.Debug:LogErrorFormat(String, Object[])
Coffee.PackageManager.Debug:LogErrorFormat(String, Object[]) (at Library/PackageCache/com.coffee.upm-git-extension@79fa88282ae1233e4841d87fd256b80f13cd8b62/Editor/Scripts/Common/Utils.cs:43)
Coffee.PackageManager.PackageUtils:UpdatePackageRequest() (at Library/PackageCache/com.coffee.upm-git-extension@79fa88282ae1233e4841d87fd256b80f13cd8b62/Editor/Scripts/Common/Utils.cs:443)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

```

**Comment by starikcetin** [comment]
Windows 10
Unity 2019.2.5f1
GitDependencyResolver 1.1.2
UpmGitExtension 0.9.1

**Comment by starikcetin** [comment]
This is weird, but putting `git+` at the beginning works:

`    "com.starikcetin.eflatun.unitycommon": "git+https://github.com/starikcetin/Eflatun.UnityCommon#0.0.1-upm",`

**Comment by starikcetin** [comment]
I got it working but it is very inconsistent. It only works if I close unity, delete the library folder, and paste the references manually into manifest.json. UpmGitExtension doesn't work.

**Comment by mob-sakai** [comment]
Hi @dimmduh @starikcetin @onMouseUp 

Sorry for my late reply.

Some files in `GitDependencyResolverForUnity` conflicts with `UpmGitExtension` .
(These packages use the same namespace `Coffee.PackageManager` )

I will fix it. :)

**Comment by mob-sakai** [comment]
Version 1.1.3 is released. Try it!

**Comment by starikcetin** [comment]
Does it work for UpmGitExtension also?

**Comment by mob-sakai** [comment]
Yes, I tested it with demo repo.
https://github.com/mob-sakai/UnityGitDependencyTest

**Comment by starikcetin** [comment]
```
Error: Unable to add package [com.starikcetin.eflatun.unitycommon@https://github.com/starikcetin/Eflatun.UnityCommon.git#0.0.3]:
  Package com.starikcetin.eflatun.unitycommon@https://github.com/starikcetin/Eflatun.UnityCommon.git#0.0.3 has invalid dependencies:
    com.starikcetin.eflatun.expansions: Version 'https://github.com/starikcetin/Eflatun.Expansions.git#0.1.1' is invalid. Expected a 'SemVer' compatible value. (NotFound)
UnityEngine.Debug:LogErrorFormat(String, Object[])
Coffee.PackageManager.Debug:LogErrorFormat(String, Object[]) (at Library/PackageCache/com.coffee.upm-git-extension@79fa88282ae1233e4841d87fd256b80f13cd8b62/Editor/Scripts/Common/Utils.cs:43)
Coffee.PackageManager.PackageUtils:UpdatePackageRequest() (at Library/PackageCache/com.coffee.upm-git-extension@79fa88282ae1233e4841d87fd256b80f13cd8b62/Editor/Scripts/Common/Utils.cs:443)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

Import from UpmGitExtension doesn't work still :(

**Comment by mob-sakai** [comment]
Hmm, works well on Unity 2018.3, but not on Unity 2019.1.
New issue: #18
