### ISSUE TITLE
Support to Branch without SemVer

### ISSUE THREAD

**Issue by rafcsoares** [mob-sakai/GitDependencyResolverForUnity#19]
Hello again @mob-sakai , i thinking if its okey to you to add support to Non-SemVer dependence resolver. I already implemented inside my project to manage this.

The logic behind is:

if (Has any previous InstalledPackage with this name && dependence.version == null)
{
//Keep any previous downloaded version
}
else if(InstalledPackage with this name not present)
{
//Download using dependence URL (probably is a head or a branch, like UPM branch)
}

**IMPLEMENTATION**

PackageMeta.cs
		
```
		public static PackageMeta FromNameAndUrl (string name, string url)
		{
. . .
				if (first.Contains ("://"))
				{
					meta.path = first;
					meta.branch = 0 < second.Length ? second : "HEAD";
					SemVersion version;
					if (!SemVersion.TryParse(meta.branch, out version))
						version = null;//empty version
					meta.version = version;
				}
. . .
		}
```

GitDependencyResolver.cs

```
		static void UninstallUnusedPackages ()
		{
. . .		
				// Collect unused pakages.
				var unusedPackages = autoInstalledPackages
					.Where (x => Path.GetFileName(x.path).StartsWith (".", Ordinal))         // Directory name starts with '.'. This is 'auto-installed package'
					.Where (x => !allDependencies.Any (y => y.name == x.name && (y.version == null || y.version == x.version)))   // No depended from other packages
					;
. . .
		}
```
```
		static void StartResolve ()
		{
. . .
			// Check all dependencies.
			foreach (var dependency in dependencies)
			{
                // Is the depended package installed already?
                bool isInstalled = installedPackages
                        .Concat(requestedPackages)
                        .Any(x => dependency.name == x.name && ((dependency.version != null && dependency.version <= x.version) || (dependency.version == null)));

				// Install the depended package later.
				if (!isInstalled)
				{
					requestedPackages.RemoveAll (x => dependency.name == x.name);
					requestedPackages.Add (dependency);
				}
			}
. . .
		}
```

Best Regards
Rafael

**Comment by mob-sakai** [comment]
Hi @rafcsoares 

Do you mean [GitDependencyResolverForUnity](https://github.com/mob-sakai/GitDependencyResolverForUnity)?

**Comment by rafcsoares** [comment]
@mob-sakai  yeah, this issue is related to this project.

Yeah. the current package does not support non-semver branchs.
if i attach to mu custom package dependence to Upm without SemVer this will be ignored

example
package.json

"dependencies": {
		"com.coffee.upm-git-extension": "https://github.com/mob-sakai/UpmGitExtension.git"
}

to fix this you must change the PackageMeta.cs to does not throw exception when trying to convert branch name to SemVer and Branch was not SemVer compatibility.

i solved this changin 3 methods (explained in my comment below)

**Comment by mob-sakai** [comment]
Ah, I see.

**Comment by mob-sakai** [comment]
To my shame, I misunderstood that this is [UpmGitExtension](https://github.com/mob-sakai/UpmGitExtension). :wink:

**Comment by mob-sakai** [comment]
@rafcsoares 
Can you create a pull request?

**Comment by rafcsoares** [comment]
Sure, i will to it @mob-sakai

**Comment by rafcsoares** [comment]
done @mob-sakai 

#20

**Comment by mob-sakai** [comment]
#21
