### ISSUE TITLE
Simply doesn't work

### ISSUE THREAD

**Issue by VirsabiMunk** [mob-sakai/GitDependencyResolverForUnity#22]
Using all three suggested methods:
SemVer on both depender and dependency, deleting library. restarting unity.

**Comment by mob-sakai** [comment]
@VirsabiMunk 
Please try to use `2.0.0-preview.1`.
https://github.com/mob-sakai/GitDependencyResolverForUnity/releases/tag/v2.0.0-preview.1

NOTE: It contains `BREAKING CHANGE`.
