### ISSUE TITLE
Install Library at Package level

### ISSUE THREAD

**Issue by cckelly** [mob-sakai/GitDependencyResolverForUnity#36]
Is it possible to install the library at the package level? In my case, I have a custom Unity package that I want to run unit tests on in our CI, but it depends on a git package.

**Comment by mob-sakai** [comment]
Do you want to automatically install the git package at project startup?
Unfortunately, since Unity 2021.1, pre-compilation user script execution has been prohibited.
Therefore, it is not possible.

**Comment by cckelly** [comment]
> Do you want to automatically install the git package at project startup? Unfortunately, since Unity 2021.1, pre-compilation user script execution has been prohibited. Therefore, it is not possible.

Thanks for the quick reply! I wrote a custom package and it depends on UniTask, I can install UniTask to a project and just link the UniTask asmdef to my package's asmdef. However, I am testing the UPM package in isolation so I can't add GitDependencyResolverForUnity to a manifest because there is no manifest. Any recommendations for how that can be handled?

**Comment by cckelly** [comment]
However, testing it out trying to pull UniTask into a custom package still ends up with compilation errors:

In my package.json:
```
  "gitDependencies": {
    "com.cysharp.unitask": "https://github.com/Cysharp/UniTask.git?path=src/UniTask/Assets/Plugins/UniTask"
  }
```

Gives me:
`error CS0246: The type or namespace name 'Cysharp' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by cckelly** [comment]
FYI @mob-sakai I opened up a new issue on the above here: https://github.com/mob-sakai/GitDependencyResolverForUnity/issues/37 - it just seems like packages aren't being pulled in at all, I've followed the README, not sure what I'm missing.
